version: '3'
name: postgres
services:
  pg_db:
    image: postgres:12.0-alpine
    container_name: pg_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      default: null
    volumes:
      - type: bind
        source: ./postgres/pg_db
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
  pgadmin4:
    image: dpage/pgadmin4:7
    container_name: pgadmin4
    depends_on:
      pg_db:
        condition: service_started
        required: true
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "8080"
        protocol: tcp
    volumes:
      - type: bind
        source: ./postgres/pgadmin4_data
        target: /var/lib/pgadmin
        bind:
          create_host_path: true
networks:
  default:
    name: postgres_default
